apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.k8s-vote/component: app
spec:
  type: ClusterIP
  selector:
    app.k8s-vote/component: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
