version: "3.9"

services:
  redis-01:
    image: redis:7
    container_name: redis-01
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./nodes/redis-01/redis.conf:/etc/redis/redis.conf

  redis-02:
    image: redis:7
    container_name: redis-02
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./nodes/redis-02/redis.conf:/etc/redis/redis.conf

  redis-03:
    image: redis:7
    container_name: redis-03
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./nodes/redis-03/redis.conf:/etc/redis/redis.conf

  redis-04:
    image: redis:7
    container_name: redis-04
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./nodes/redis-04/redis.conf:/etc/redis/redis.conf

  redis-05:
    image: redis:7
    container_name: redis-05
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./nodes/redis-05/redis.conf:/etc/redis/redis.conf

  redis-06:
    image: redis:7
    container_name: redis-06
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./nodes/redis-06/redis.conf:/etc/redis/redis.conf
